image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'echo "Looking good today bb"'
    command: 'ngrok authtoken "$ngrokAuth'
    command: 'ngrok tcp 3306'

ports:
  - port: 3306
  - port: 4040

  # Okay seriously this is dumb. Last branch before I go to bed.